//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunBeam.Domain.Models
{
    using SunBeam.Domain;
    using System;
    using System.Collections.Generic;

    public partial class PurcheaseReturnDetails: BaseEntity
    {
        public int Id { get; set; }
        public int PurchaseReturnId { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public decimal UnitePrice { get; set; }
        public string Data { get; set; }
        public decimal Quantity { get; set; }
        public decimal Discount { get; set; }
        public decimal TotalPrice { get; set; }
     
    }
}
